name: ridy
description: Rider Application of Taxi

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.6+30

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  artemis: 7.2.6-beta
  country_code_picker: ^2.0.2
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  facebook_app_events: 0.15.0
  file_picker: ^4.5.0
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_ui: ^1.5.5
  flutter_google_places_hoc081098: ^1.0.1
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^3.0.2
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.2
  gql: 0.13.1-alpha+1635149947792
  graphql_flutter: ^5.0.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  lifecycle: ^0.4.3
  lottie: ^1.2.2
  marquee: ^2.2.1
  meta: ^1.3.0
  osm_nominatim: ^2.0.1
  package_info_plus: ^1.4.0
  sms_autofill: ^2.1.2
  timeago_flutter: ^1.1.0
  url_launcher: ^6.0.20
  velocity_x: ^3.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - images/default-user-image.png
    - images/expanding_marker.json
    - images/3532-car.json
    - images/marker_pickup.png
    - images/marker_taxi.png
    - images/marker_destination.png
    - images/logo.png
    - images/downtown.png

flutter_intl:
  enabled: true