name: ridy
description: Driver application of Ridy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.8+36

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  artemis: 7.2.6-beta
  country_code_picker: ^2.0.2
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  file_picker: ^4.3.3
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_ui: ^1.5.5
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^1.0.0
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.1.1
  gql: 0.13.1-alpha+1635149947792
  graphql_flutter: ^5.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  lifecycle: ^0.4.2
  lottie: ^1.1.0
  marquee: ^2.2.0
  map_launcher: ^2.1.2
  meta: ^1.3.0
  package_info_plus: ^1.3.0
  sms_autofill: ^2.1.0
  url_launcher: ^6.0.18
  velocity_x: ^3.4.0

  

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/downtown.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/default-user-image.png
    - images/logo.png
    - images/marker_pickup.png
    - images/marker_destination.png
    - images/downtown.png

flutter_intl:
  enabled: true
